// src/localization/Languages.ts
import LocalizedStrings from 'react-native-localization';
import AsyncStorage from '@react-native-async-storage/async-storage';

type SupportedLang = 'en' | 'zh-Hans' | 'zh-Hant';

const strings = new LocalizedStrings({
  en: {
    home: "Home",
    howToUse: "How To Use",
    terms: "Terms & Conditions",
    helpFeedback: "Help & Feedback",
    logout: "Logout",
    logoutConfirmTitle: "Logout?",
    logoutConfirmMessage: "Are you sure you want to logout from this account?",
    yes: "Yes",
    no: "No",
    changeLanguage: "Change Language",
    selectLanguage: "Select your preferred language:",
    english: "English",
    chineseSimplified: "Simplified Chinese",
    chineseTraditional: "Traditional Chinese",
    close: "Close",
    loan: "Loan",
    currentLoan: "Current Loan Amount",
    repayLoan: "Repay Loan",
    loanRepayment: "Loan Repayment",
    LoanInformation: "Loan Information",
    wantTo: "Want To Borrow More?",
    RepaidAmount: "Repaid Amount",
    LoremIpsum: "Lorem Ipsum",
    LoanHistory: "Loan History",
    Help: "Help",
    HelpCenter: "Help Center",
    FAQ: "FAQ",
    ContactSupport: "Contact Support",
    RequestSupport: "Request Support",
    Subject: "Subject",
    Entersubject: "Enter subject",
    Message: "Message",
    EnterMess: "Enter message",
    Continue: "Continue",
    Profile: "Profile",
    Facebook: "Facebook",
    Gender: "Gender",
    Dob: "DOB",
    Age: "Age",
    PhoneNumber: "Phone Number",
    Address: "Address",
    State: "State",
    EditProfile: "Edit Profile",
    ApplyforLoa: "Apply for a Loan",
    EnterAmount: "Enter Amount",
    PreviewInterestRate: "Preview Interest Rate",
    Confirm: "Confirm",
    ChangePasswordScreen: "Change Password",
    EnteryourEmail: "Enter your email",
    Password: "Password",
    LogIn: "Log In",
    fullname: "Enter your full name",
    FuName: "Full Name",
    Enteryourpassword: "Enter your password",
    DateBirth: "Date of Birth",
    Cancel: "Cancel",
    Done: "Done",
    SaveChanges: "Save Changes",
    PrivacyPolicy: "Privacy Policy",
    DeleteAccount: "Delete Account",
    deleteText: "Are you sure you want to delete your account? You’ll lose all your data and access permanently.",
    Delete: "Delete",
    Confirmdelete: "Confirm delete",
    Notifications: "Notifications",
  },
  // 簡體中文
  'zh-Hans': {
    home: "首页",
    howToUse: "如何使用",
    terms: "条款与条件",
    helpFeedback: "帮助与反馈",
    logout: "登出",
    logoutConfirmTitle: "登出？",
    logoutConfirmMessage: "您确定要登出此账户吗？",
    yes: "是",
    no: "否",
    changeLanguage: "更改语言",
    selectLanguage: "选择您偏好的语言：",
    english: "英文",
    chineseSimplified: "简体中文",
    chineseTraditional: "繁體中文",
    close: "关闭",
    loan: "贷款",
    currentLoan: "当前贷款金额",
    repayLoan: "偿还贷款",
    loanRepayment: "贷款偿还",
    LoanInformation: "贷款信息",
    wantTo: "想要借更多吗？",
    RepaidAmount: "已偿还金额",
    LoremIpsum: "乱数假文",
    LoanHistory: "贷款历史",
    Help: "帮助",
    HelpCenter: "帮助中心",
    FAQ: "常见问题",
    ContactSupport: "联系客服",
    RequestSupport: "请求支持",
    Subject: "主题",
    Entersubject: "输入主题",
    Message: "信息",
    EnterMess: "输入消息",
    Continue: "继续",
    Profile: "个人资料",
    Facebook: "Facebook",
    Gender: "性别",
    Dob: "出生日期",
    Age: "年龄",
    PhoneNumber: "电话号码",
    Address: "地址",
    State: "省份",
    EditProfile: "编辑资料",
    ApplyforLoa: "申请贷款",
    EnterAmount: "输入金额",
    PreviewInterestRate: "预览利率",
    Confirm: "确认",
    ChangePasswordScreen: "更改密码",
    EnteryourEmail: "输入您的邮箱",
    Password: "密码",
    LogIn: "登录",
    fullname: "输入您的姓名",
    FuName: "姓名",
    Enteryourpassword: "输入您的密码",
    DateBirth: "出生日期",
    Cancel: "取消",
    Done: "完成",
    SaveChanges: "保存更改",
    PrivacyPolicy: "隐私政策",
    DeleteAccount: "删除账户",
    deleteText: "确定要删除账户吗？所有数据将永久删除。",
    Delete: "删除",
    Confirmdelete: "确认删除",
    Notifications: "通知",
  },
    // 繁體中文
  'zh-Hant': {
    home: "首頁",
    howToUse: "如何使用",
    terms: "條款與條件",
    helpFeedback: "幫助與回饋",
    logout: "登出",
    logoutConfirmTitle: "登出？",
    logoutConfirmMessage: "您確定要登出此帳戶嗎？",
    yes: "是",
    no: "否",
    changeLanguage: "更改語言",
    selectLanguage: "選擇您偏好的語言：",
    english: "英文",
    chineseSimplified: "簡體中文",
    chineseTraditional: "繁體中文",
    close: "關閉",
    loan: "貸款",
    currentLoan: "目前貸款金額",
    repayLoan: "還款",
    loanRepayment: "貸款還款",
    LoanInformation: "貸款資訊",
    wantTo: "想要借更多嗎？",
    RepaidAmount: "已還金額",
    LoremIpsum: "隨機文字",
    LoanHistory: "貸款紀錄",
    Help: "幫助",
    HelpCenter: "幫助中心",
    FAQ: "常見問題",
    ContactSupport: "聯絡客服",
    RequestSupport: "請求支援",
    Subject: "主題",
    Entersubject: "輸入主題",
    Message: "訊息",
    EnterMess: "輸入訊息",
    Continue: "繼續",
    Profile: "個人資料",
    Facebook: "Facebook",
    Gender: "性別",
    Dob: "出生日期",
    Age: "年齡",
    PhoneNumber: "電話號碼",
    Address: "地址",
    State: "州/縣",
    EditProfile: "編輯個人資料",
    ApplyforLoa: "申請貸款",
    EnterAmount: "輸入金額",
    PreviewInterestRate: "預覽利率",
    Confirm: "確認",
    ChangePasswordScreen: "變更密碼",
    EnteryourEmail: "輸入電子郵件",
    Password: "密碼",
    LogIn: "登入",
    fullname: "輸入全名",
    FuName: "姓名",
    Enteryourpassword: "輸入密碼",
    DateBirth: "出生日期",
    Cancel: "取消",
    Done: "完成",
    SaveChanges: "儲存變更",
    PrivacyPolicy: "隱私政策",
    DeleteAccount: "刪除帳戶",
    deleteText: "您確定要刪除帳戶嗎？所有資料將永久刪除。",
    Delete: "刪除",
    Confirmdelete: "確認刪除",
    Notifications: "通知",
  },
});

// Load saved language or set default 'zh'
export const loadLanguage = async () => {
  const savedLang = await AsyncStorage.getItem('appLanguage');
  if (savedLang && (savedLang === 'en' || savedLang === 'zh-Hans' || savedLang === 'zh-Hant')) {
    strings.setLanguage(savedLang);
  } else {
    strings.setLanguage('zh-Hant'); // 預設繁體中文
  }
};

// Change language
export const changeAppLanguage = async (lang: SupportedLang) => {
  strings.setLanguage(lang);
  await AsyncStorage.setItem('appLanguage', lang);
};

export default strings;
